# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d115de1242f1583d8430dde1535c994db40ad8bf9ccb9b7ebe7f0f29fd869f7bdf4b884590d8bb584cb5140c0cdb69508d20472a2f7032265309f93281c7cb05

test:
  secret_key_base: f21a0c84b8bfdf55631db78647aa00ff9825917a8813a5c866d797f88f36b250a9e13ea0a88e3c932fe1b2b295a9a3c3e83f6d6874d32b820f12aa61edafac1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
